                                <li class="w3-right-align"
                                    id="${buttons_li_id_prefix}_buttonsLi_${buttons_li_id_suffix}">
                                    <button class="w3-black w3-button"
                                            name="${buttons_li_id_prefix}_programClearButton_${buttons_li_id_suffix}"
                                            onclick="GuideModule.clearProgramRadioButtonGroup('${buttons_li_id_prefix}', '${buttons_li_id_suffix}')">Clear
                                    </button>
                                    <button class="w3-button w3-disabled w3-red"
                                            name="${buttons_li_id_prefix}_programRecordButton_${buttons_li_id_suffix}"
                                            onclick="GuideModule.recordProgram('${buttons_li_id_prefix}', '${buttons_li_id_suffix}')">Record
                                    </button>
                                </li>