                        <li class="w3-container"
                            id="${date_programs_li_id_prefix}_dateProgramsLi_${date_programs_li_id_suffix}"
                            style="display: none; padding: 0;">
                            <ul class="w3-ul w3-border-no"
                                id="${date_programs_li_id_prefix}_dateProgramsUl_${date_programs_li_id_suffix}">
                                ${date_programs_lis}
                            </ul>
                        </li>