<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://www.w3schools.com/w3css/4/w3.css"
          rel="stylesheet"/>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1"
          name="viewport">
    <style>
        body {
            display: flex;
        }

        html, body {
            height: 100%;
            margin: 0;
            width: 100%;
        }

        div {
            margin: auto;
        }
    </style>
    <title>IPTVProxy ${iptv_proxy_version}</title>
</head>
<body>
    <div>
        <h1>${http_error_code} - ${http_error_title}</h1>
        <h3>${http_error_details}</h3>
    </div>
</body>
</html>