    <div class="w3-border w3-container w3-left"
         id="guideDiv"
         style="overflow-y: auto; width: 100%;">
        <div class="w3-container">
            <ul class="w3-ul"
                id="guideUl"
                style="display: none;">
${guide_lis}
                <li class="w3-border-0 w3-center"
                    id="noMatchingProgramLi"
                    style="display: none;">
                    <p>No programs matching the search pattern found</p>
                </li>
            </ul>
        </div>
    </div>